### ISSUE TITLE
Neue Connection bei jedem WebSocket Event

### ISSUE THREAD

**Issue by UlrichFrank** [oxytu/deconz-to-mqtt#2]
Wenn ic es recht verstehe öffnest du mit jedem Event dass du von deCONZ bekommst eine neue Connection zum MQTT Broker (und schließt sie nie). Übliches Client Verhalten: Connection bleibt dauerhaft offen (alle 60s Jeep Alice) https://www.hivemq.com/blog/mqtt-essentials-part-3-client-broker-connection-establishment/. Grund?

**Comment by oxytu** [comment]
This is currently a design consideration to keep the implementation simple. Due to the usage of asynchronous mechanisms, a persistent connection would require some form of connection pooling. Feel free to provide an implementation for this.
