### ISSUE TITLE
Mqtt server password

### ISSUE THREAD

**Issue by schmurtzm** [oxytu/deconz-to-mqtt#3]
Hi, may be it should be adressed to AIOMQTT I don't know but I ask :  
is it possible to connect deconz-to-mqtt on a MQTT server with a login & password ?

Thank you.

**Comment by oxytu** [comment]
Actually, have a look at 
https://pypi.org/project/paho-mqtt/1.1/ - especially the function 
username_pw_set(username, password=None)

Needs some implementation effort, not supported out of the box.

Regards,
Tobias

**Comment by oxytu** [comment]
Actually, have a look at 
https://pypi.org/project/paho-mqtt/1.1/ - especially the function 
username_pw_set(username, password=None)

Needs some implementation effort, not supported out of the box.

Regards,
Tobias

**Comment by oxytu** [comment]
Actually, have a look at 
https://pypi.org/project/paho-mqtt/1.1/ - especially the function 
username_pw_set(username, password=None)

Needs some implementation effort, not supported out of the box.

Regards,
Tobias

**Comment by schmurtzm** [comment]
Thanks, thanks, thanks 😅
For the moment I’ve just activated anonymous login on my mqtt server. (I know, it’s bad).

By the way you should add a « / » at the end of this line of the config file :
rest_url: http://openhabianpi/api/<<« your-api-key-here »>>

Otherwise it doesn’t work.
Thanks for this very useful python script !

**Comment by oxytu** [comment]
Hi, thank you for the feedback. I just added the slash to the example configuration. The rest is still left to do, as I personally currently have no use-case for this (mqtt only runs locally here).
